apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # For app pipeline
  - pipeline/pipeline.yaml
  - pipeline/event-listener.yaml
  - pipeline/trigger-binding.yaml
  - pipeline/trigger-template.yaml
  - pipeline/task.yaml
  # For test reports
  - test-reports/deployment.yaml
  - test-reports/service.yaml
  - test-reports/route.yaml