apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: sample-app-event-listener-dev
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - ref: sample-app-trigger-binding-dev
      template:
        ref: sample-app-trigger-template-dev
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-sample-app-event-listener-dev
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: sample-app-event-listener-dev
  annotations:
    openshift.io/host.generated: "true"
spec:
  to:
    kind: Service
    name: el-sample-app-event-listener-dev
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None
