apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: kubernetes.io/basic-auth
data:
  username: Y29vbGJveTA5NjE=
  password: Z2hwX1VrcmZyc0VTbFlJSUVKWDRjWllKejg3a0hKMU1DNzJCYU43Tw