apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: kubernetes.io/basic-auth
data:
  username: Y29vbGJveTA5NjE=
  password: Z2l0aHViX3BhdF8xMUFEQzdPUkkwVENyOWhWaVhUV0lkX09ucWxsSUN5SFpzYWo4dGhhbkE4R0padUFGN1BZZmFlUHBpbXA5UDNzUmdZSFoySElWTFJ2QTR5SjZ1