apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: sample-app-trigger-binding-dev
spec:
  params:
    - name: GIT_REPO_URL
      value: $(body.repository.clone_url)
    - name: GIT_REPO_NAME
      value: $(body.repository.name)
    - name: GIT_REVISION
      value: $(body.head_commit.id)
