apiVersion: tekton.dev/v1 # or tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-taskrun
spec:
  taskRef:
    name: buildah
    kind: ClusterTask
  computeResources:
    limits:
      memory: "2Gi"