kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-view
  labels:
    app: it-sample-view
spec:
  selector:
    matchLabels:
      deployment: it-sample-view
  template:
    metadata:
      labels:
        deployment: it-sample-view
        app: it-sample-view
    spec:
      containers:
        - name: sample-view
          image: image-registry.openshift-image-registry.svc:5000/jiadchen-dev/sample-view:latest
          env:
            - name: API_BASE_URL
              value: https://it-sample-app-jiadchen-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com
