kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-view
  labels:
    app: dev-sample-view
spec:
  selector:
    matchLabels:
      deployment: dev-sample-view
  template:
    metadata:
      labels:
        deployment: dev-sample-view
        app: dev-sample-view
    spec:
      containers:
        - name: sample-view
          env:
            - name: API_BASE_URL
              value: https://sample-app-jiadchen-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com
