kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-view
  labels:
    app: dev-sample-view
spec:
  selector:
    matchLabels:
      deployment: dev-sample-view
  template:
    metadata:
      labels:
        deployment: dev-sample-view
        app: dev-sample-view
    spec:
      containers:
        - name: sample-view
          image: image-registry.openshift-image-registry.svc:5000/jiadchen-dev/sample-view:c7da844a71f7d1d5b049128c9cb57d893ad42a32
          env:
            - name: API_BASE_URL
              value: https://dev-sample-app-jiadchen-dev.apps.rm3.7wse.p1.openshiftapps.com
