kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-app
  labels:
    app: it-sample-app
spec:
  selector:
    matchLabels:
      deployment: it-sample-app
  template:
    metadata:
      labels:
        deployment: it-sample-app
        app: it-sample-app
    spec:
      containers:
        - name: sample-app
          image: image-registry.openshift-image-registry.svc:5000/jiadchen-dev/sample-app:f34b2199612400ea0c34796a82b416389daae137
