kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-app
  labels:
    deployment: dev-sample-app
spec:
  selector:
    matchLabels:
      app: dev-sample-app
  template:
    metadata:
      labels:
        app: dev-sample-app
    spec:
      containers:
        - name: sample-app
          image: image-registry.openshift-image-registry.svc:5000/jiadchen-dev/sample-app:c7da844a71f7d1d5b049128c9cb57d893ad42a32